"""Add partial_failure to RunStatusEnum

Revision ID: 3d05f5f5c850
Revises: fb5e7f5e79ef
Create Date: 2026-09-19 13:19:03.609144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d05f5f5c850'
down_revision: Union[str, Sequence[str], None] = 'fb5e7f5e79ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE runstatusenum ADD VALUE IF NOT EXISTS 'partial_failure'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
